name: example
description: An absolute bare-bones web app.
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  dawn:
    path: ../
dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  nexlints: ^1.0.1
