name: example
description: A Dawn app
publish_to: none
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  dawn:
    path: ../
dev_dependencies:
  build_runner: ^2.2.0
  build_web_compilers: ^3.2.5
  dawn_lints: ^2.0.1
