name: example
description: A Dawn app
publish_to: none
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  dawn:
    path: ../
dev_dependencies:
  build_runner: ^2.2.1
  build_web_compilers: ^3.2.6
  dawn_lints: ^3.0.0
