name: example
description: A Dawn app
publish_to: none
environment:
  sdk: ">=2.19.4 <3.0.0"
dependencies:
  dawn:
    path: ../
dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  dawn_lints: ^3.1.0
