name: dawn
description: Dawn is a Dart Web Framework that lets developers to develop UIs with a widget model similar to Flutter. Dawn applications are compiled to JavaScript and are painted using HTML and CSS.
version: 5.0.6
homepage: https://github.com/Hawmex/dawn
repository: https://github.com/Hawmex/dawn
environment:
  sdk: ">=2.17.5 <3.0.0"
dev_dependencies:
  dawn_lints: ^2.0.1
executables:
  dawn:
dependencies:
  args: ^2.3.1
  shelf: ^1.3.2
  shelf_static: ^1.1.1
