name: dawn
description: A Dart Web framework inspired by Flutter.
version: 1.1.0
homepage: https://github.com/Hawmex/dawn
repository: https://github.com/Hawmex/dawn
environment:
  sdk: ">=2.15.1 <3.0.0"
dev_dependencies:
  dawn_lints: ^1.0.0
