name: dawn
description: Dawn is a Dart web framework that lets developers create UIs with a widget model similar to Flutter. Dawn apps are compiled into JS and painted with HTML & CSS.
version: 7.0.1
homepage: https://dawn-dev.netlify.app
repository: https://github.com/Hawmex/dawn
environment:
  sdk: ">=2.19.4 <3.0.0"
executables:
  dawn:
dev_dependencies:
  dawn_lints: ^3.1.0
dependencies:
  args: ^2.4.0
  js: ^0.6.7
