name: dawn
description: Dawn is a Dart web framework that lets developers create UIs with a widget model similar to Flutter. Dawn apps are compiled into JS and painted with HTML & CSS.
version: 6.0.0-dev.8
homepage: https://dawn-dev.netlify.app
repository: https://github.com/Hawmex/dawn
environment:
  sdk: ">=2.18.0 <3.0.0"
executables:
  dawn:
dev_dependencies:
  dawn_lints: ^2.0.1
dependencies:
  args: ^2.3.1
  js: ^0.6.4
